# Generated by Django 4.0.6 on 2022-10-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0001_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='allowed_tags',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_quizzes',
        ),
    ]
