# Generated by Django 4.1.3 on 2022-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moelasware", "0002_remove_test_allowed_tags_remove_test_num_quizzes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="name",
            field=models.TextField(default="Quiz"),
            preserve_default=False,
        ),
    ]
