# Generated by Django 4.1.3 on 2022-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moelasware", "0004_quiz_approved_quiz_creation_date_quiz_finished_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
