#!/bin/sh
PGPASS=$(cat $POSTGRES_PASSWORD_FILE)
PGNAME="localee"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $PGNAME WITH PASSWORD '$PGPASS';
  CREATE DATABASE $PGNAME;
  GRANT ALL PRIVILEGES ON DATABASE $PGNAME TO $PGNAME;
  \c $PGNAME;
  GRANT ALL PRIVILEGES ON SCHEMA public TO $PGNAME;
EOSQL
